repos:
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
    - id: isort
-   repo: local
    hooks:
      - id: system
        name: MyPy
        entry: poetry run mypy .
        pass_filenames: false
        language: system
