version: "3.8"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - django-static:/var/www/django/static
    ports:
      - '80:80'
    depends_on:
      - web

  web:
    build:
      target: production_build
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: production

    restart: unless-stopped
    command: sh ./docker/django/gunicorn.sh
